# Change prefix to Ctrl+a (easier to reach)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Intuitive splits
bind | split-window -h
bind - split-window -v

# Enable mouse support
set -g mouse on

# Start windows/panes at 1 (not 0)
set -g base-index 1
setw -g pane-base-index 1

# Reload config
bind r source-file ~/.tmux.conf \; display "Config reloaded"

# Arrow keys move between panes
bind Left  select-pane -L
bind Down  select-pane -D
bind Up    select-pane -U
bind Right select-pane -R

# Ctrl+Arrow resizes panes by 5
bind -r C-Left  resize-pane -L 5
bind -r C-Down  resize-pane -D 5
bind -r C-Up    resize-pane -U 5
bind -r C-Right resize-pane -R 5

# New window in current directory
bind c new-window -c "#{pane_current_path}"

# Safer pane/window killing
bind x confirm-before -p "Kill pane #P? (y/n)" kill-pane
bind X confirm-before -p "Kill window #W? (y/n)" kill-window

# Copy / Paste
set -g set-clipboard on
setw -g mode-keys vi

bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# Larger scrollback
set -g history-limit 1000000

# Better responsiveness
set -sg escape-time 0

# plugins
set -g @plugin 'jaclu/tmux-menus'

run '~/.tmux/plugins/tpm/tpm'